# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

jobs:
- job: TestNGReportParsingTest
  pool:
    vmImage: $(vmImageVar)
#    vmImage: 'vs2017-win2016'
#    vmImage: 'Ubuntu 16.04'
#    vmImage: 'macOS-10.13'

  steps:
  - script: ls
    displayName: ls command

  - task: Maven@3
    displayName: Maven Package
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      goals: '--settings settings-parser-project.xml clean package'

  - script: ls
    displayName: $(vmImageVar) env

- template: artifacts.yml
